<?php
namespace common\models;

use Yii;
use yii\db\ActiveRecord;

class Regions extends ActiveRecord
{
    public static function getDb()
    {
        return Yii::$app->geo; // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%_regions}}';
    }
}
